services:
  - type: web
    name: social-media-backend
    env: node
    repo: https://github.com/AmrHamoudaX/social_media.git
    branch: main
    plan: free
    buildCommand: |
      cd backend
      npm install
      npm run migration:up
    startCommand: |
      cd backend
      npm start
    envVars:
      - key: DB_URL
        fromDatabase:
          name: social-media-db
      - key: SECRET
        value: "super_secret_key"
      - key: PORT
        value: "3000"

  - type: postgres
    name: social-media-db
    plan: free

  - type: static
    name: social-media-frontend
    repo: https://github.com/AmrHamoudaX/social_media.git
    branch: main
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://social-media-backend.onrender.com
